### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by davidsingal** [onel0p3z/realtime-maps-express-io#1]
Es mejor no incluir la carpeta node_modules en git. Mirate .gitignore y package.json.

Puedes intentar poner el centro del mapa depués de la localización.

El resto está muy bien, claro que se puede siempre mejorar pero para ser un ejercicio está genial.

Cualquier duda me dices :).

**Comment by onel0p3z** [comment]
Ya habia agregado un .gitignore en la carpeta de node_modules pero no se que paso; con respecto a el package.json me falta poblarlo.

Ya esta centrando el mapa despues de cada localizacion.

Muchas gracias por tus comentarios! Ayudan a corregir y continuar aprendiendo :D
